spring.application.name=API_GATEWAY
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=lb://COURSE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/course/**

spring.cloud.gateway.routes[2].id=enrollment-service
spring.cloud.gateway.routes[2].uri=lb://ENROLLMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enrollment/**

logging.level.org.springframework.cloud.gateway=DEBUG



